package Boundry;


import Control.Control;
import Entity.FileHandler;
import Entity.Member;
import java.io.BufferedWriter;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Steffen
 */
public class GUI extends javax.swing.JFrame {
    
    

    /**
     * Creates new form GUI
     */
    Control con = new Control();
    DefaultListModel model1 = new DefaultListModel();
    DefaultListModel model2 = new DefaultListModel();
    String teamName;
    String newMember;
    String[] stumperNy = new String[5];
    
    
    
    
    
    
    public GUI() {
        
        initComponents();
        jListMembers.setModel(model1);
        jListTeam.setModel(model2);
        for (Member m : con.getMembers()){
            model1.addElement(m);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListMembers = new javax.swing.JList();
        Persons = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTeam = new javax.swing.JList();
        Team = new javax.swing.JLabel();
        SaveTeam = new javax.swing.JButton();
        jListNameTeam = new javax.swing.JTextField();
        jLabelNavnGivTeam = new javax.swing.JLabel();
        jLabelAddNewMember = new javax.swing.JLabel();
        NameMember = new javax.swing.JTextField();
        adm = new javax.swing.JTextField();
        kre = new javax.swing.JTextField();
        ana = new javax.swing.JTextField();
        fin = new javax.swing.JTextField();
        AddNewMember = new javax.swing.JButton();
        ResetNewMember = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        administrativ = new javax.swing.JLabel();
        kreativitet = new javax.swing.JLabel();
        Analytisk = new javax.swing.JLabel();
        Fin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListMembers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListMembers);

        Persons.setText("Persons");

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        jListTeam.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListTeam);

        Team.setText("Team");

        SaveTeam.setText("SaveTeam");
        SaveTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveTeamActionPerformed(evt);
            }
        });

        jListNameTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListNameTeamActionPerformed(evt);
            }
        });

        jLabelNavnGivTeam.setText("Giv dit team et navn");

        jLabelAddNewMember.setText("Add a member");

        NameMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameMemberActionPerformed(evt);
            }
        });

        AddNewMember.setText("Add");
        AddNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewMemberActionPerformed(evt);
            }
        });

        ResetNewMember.setText("reset");
        ResetNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetNewMemberActionPerformed(evt);
            }
        });

        Name.setText("Name");

        administrativ.setText("Adm");

        kreativitet.setText("Kre");

        Analytisk.setText("Ana");

        Fin.setText("Fin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(Persons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Team, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(administrativ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kreativitet)
                    .addComponent(Analytisk)
                    .addComponent(Fin)
                    .addComponent(Name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddNewMember))
                            .addComponent(jScrollPane1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ResetNewMember))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaveTeam, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jListNameTeam)
                            .addComponent(jLabelNavnGivTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAddNewMember)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(NameMember, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                .addComponent(adm, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ana, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Persons)
                    .addComponent(Team))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Add)
                        .addGap(37, 37, 37)
                        .addComponent(Remove))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNavnGivTeam)
                                .addGap(18, 18, 18)
                                .addComponent(jListNameTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(SaveTeam))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28)
                .addComponent(jLabelAddNewMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(administrativ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kreativitet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Analytisk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetNewMember)
                    .addComponent(Fin)
                    .addComponent(AddNewMember))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        List selected = jListTeam.getSelectedValuesList();
        
        for(Object o : selected){
            model2.removeElement(o);
            model1.addElement(o);
        }
    }//GEN-LAST:event_RemoveActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        List selected = jListMembers.getSelectedValuesList();
        
        for(Object o : selected){
            model1.removeElement(o);
            model2.addElement(o);
        }
        
        
        
    }//GEN-LAST:event_AddActionPerformed
    
    
    
    public void addNewMember(){

        
        String n = String.format("%s, %s, %s, %s, %s", NameMember.getText(), adm.getText(), kre.getText(), 
        ana.getText(), fin.getText());
    
    try(PrintWriter out = new PrintWriter(new BufferedWriter(new FileWriter("Members.txt", true)))) {
        out.println(n);
    } 
    catch (IOException e) {
        //exception handling left as an exercise for the reader
    }
    model1.addElement(n);


}
    
    
    private void SaveTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveTeamActionPerformed
        
        try {
            try (BufferedWriter buffer = new BufferedWriter(new FileWriter(new File(jListNameTeam.getText()),true))) {
                for(int i = 0 ; i<model2.size();i++){
                    buffer.write(model2.getElementAt(i).toString()+ "\n");
                    buffer.flush();
                }   }

    } catch (IOException ex) {
            System.out.println(ex.getMessage());
    }
       


    }//GEN-LAST:event_SaveTeamActionPerformed

    private void jListNameTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListNameTeamActionPerformed
        
        
    }//GEN-LAST:event_jListNameTeamActionPerformed

    private void NameMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameMemberActionPerformed

    private void AddNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewMemberActionPerformed

        addNewMember();
        
        
        
    }//GEN-LAST:event_AddNewMemberActionPerformed

    private void ResetNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetNewMemberActionPerformed
        NameMember.setText("");
        adm.setText("");
        kre.setText("");
        ana.setText("");
        fin.setText("");
    }//GEN-LAST:event_ResetNewMemberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton AddNewMember;
    private javax.swing.JLabel Analytisk;
    private javax.swing.JLabel Fin;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameMember;
    private javax.swing.JLabel Persons;
    private javax.swing.JButton Remove;
    private javax.swing.JButton ResetNewMember;
    private javax.swing.JButton SaveTeam;
    private javax.swing.JLabel Team;
    private javax.swing.JTextField adm;
    private javax.swing.JLabel administrativ;
    private javax.swing.JTextField ana;
    private javax.swing.JTextField fin;
    private javax.swing.JLabel jLabelAddNewMember;
    private javax.swing.JLabel jLabelNavnGivTeam;
    private javax.swing.JList jListMembers;
    private javax.swing.JTextField jListNameTeam;
    private javax.swing.JList jListTeam;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kre;
    private javax.swing.JLabel kreativitet;
    // End of variables declaration//GEN-END:variables
}
